# Generated by Django 5.2.5 on 2025-09-26 16:48

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rachais', '0002_alter_expense_options_alter_expense_paid_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do Grupo'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('creator'), name='uniq_group_name_per_creator_ci'),
        ),
    ]
