# Generated by Django 5.2.5 on 2025-10-28 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rachais', '0003_alter_group_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='split_method',
            field=models.CharField(choices=[('EQUAL', 'Dividir igualmente'), ('UNEQUAL_VALUE', 'Dividir por valores exatos'), ('UNEQUAL_PERCENTAGE', 'Dividir por porcentagem')], default='EQUAL', max_length=20),
        ),
        migrations.CreateModel(
            name='ExpenseSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_owed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor devido ')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='rachais.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('expense', 'user')},
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='participants',
            field=models.ManyToManyField(related_name='expenses_participated', through='rachais.ExpenseSplit', to=settings.AUTH_USER_MODEL),
        ),
    ]
