build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt # <-- CORRIGIDO
      
      - name: Run collectstatic
        run: python manage.py collectstatic --noinput # <-- CORRIGIDO
      
      - name: Cleaning testing files
        run: |
          if [ -f db.sqlite3 ]; then rm db.sqlite3; fi # <-- CORRIGIDO
          if [ -f .env ]; then rm .env; fi
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/
