name: Build and deploy Python app to Azure Web App - Rachaiapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python version
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Confirme se esta é a versão correta do Python para seu projeto

    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    
    - name: Install dependencies
      # Comando corrigido para instalar a partir do requirements.txt na raiz
      run: pip install -r requirements.txt
    
    - name: Run collectstatic
      # Este comando é essencial para que o Django encontre seus arquivos estáticos em produção
      run: python manage.py collectstatic --noinput
    
    - name: Cleaning unnecessary files
      # Remove arquivos que não precisam ir para o ambiente de produção
      run: |
        if [ -f db.sqlite3 ]; then rm db.sqlite3; fi
        if [ -f .env ]; then rm .env; fi
        
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: python-app
        path: |
          .
          !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Necessário para o login OIDC com Azure

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: python-app
        path: .

    - name: Login to Azure
      uses: azure/login@v2
      with:
        # Recomendo usar nomes mais genéricos para os secrets no GitHub
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'Rachaiapp' # Verifique se este é o nome exato do seu App Service na Azure
        slot-name: 'Production'
        package: . # O ponto (.) indica para o Azure usar o diretório atual como pacote de deploy
