deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Necessário para o login OIDC
      contents: read
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: . # Extrai os arquivos para o diretório atual

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Rachaiapp'
          slot-name: 'Production'
          package: . # Diz para o deploy usar os arquivos do diretório atual
