name: Build and deploy Python app to Azure Web App - Rachaiapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python version
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Run collectstatic
      run: python manage.py collectstatic --noinput
    
    - name: Cleaning unnecessary files
      run: |
        if [ -f db.sqlite3 ]; then rm db.sqlite3; fi
        if [ -f .env ]; then rm .env; fi
        
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: python-app
        path: |
          .
          !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: python-app
        path: .

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3572C8220008463E9ACBB479749BAFDD }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B6B3828879649468F0316D48FF7275A }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F54F637B8CBA4EABD4B1168634AE9CF }}

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'Rachaiapp'
        slot-name: 'Production'
        package: .
