name: Build and deploy Python app to Azure Web App - rachai

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Check Chrome
        run: |
          which google-chrome || which chrome || true
          google-chrome --version || true

      - name: Kill orphan chrome (best effort)
        run: |
          pkill -f chrome || true
          pkill -f chromium || true

      - name: Run tests (no parallel)
        env:
          CI: "true"
        run: |
          python manage.py test --parallel 1 || echo "Tests failed but continuing to deploy"

      - name: Collect static files
        run: python manage.py collectstatic --noinput

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: .
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Create deployment package
        run: |
          zip -r app.zip . -x "venv/*" ".git/*" ".github/*" "*.sqlite3" "__pycache__/*"

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'rachai'
          slot-name: 'Production'
          package: app.zip
